name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # roda 1x por dia
  workflow_dispatch:       # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # importante para commitar no branch output
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: victorhferreira016
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
